name = "MCTBetaScaling"
uuid = "89e7ec30-1fdf-11ee-08a6-c5e7866bad12"
authors = ["s158686 "]
version = "0.0.1"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModeCouplingTheory = "6cad4188-63cb-4528-a10f-dbb409b456c6"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
CairoMakie = "0.15.4"
FFTW = "1.9.0"
LinearAlgebra = "1.11.0"
SpecialFunctions = "2"
